# Site settings
title: Stranice predmeta Duboko učenje (FER)
email: ivan.kreso@fer.hr
description: "Materijali i laboratorijske vježbe iz predmeta Duboko Učenje"
baseurl: ""
url: "http://dlunizg.github.io"
github_username:  dlunizg

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

